---
# Minion configuration schema

# Notes:
# - The frontend may want to just fetch the categories first and then fetch the contents of each category separately
# lazily

# Version of Minion this schema configuration is applicable to
version: "foo"

# The root set of categories
categories:
  # IPC Configuration
  - name: "ipc"
    description: "TODO"
    categories:
      # IPC Configuration :: gRPC
      - name: "grpc"
        description: "TODO"
        config:
          - name: "Host"
            type:
              name: "host-with-port"
            description: "TODO"
            tip: "TODO"
            key: "/ipc/grpc/host"
            example: "TODO"
          - name: "Properties"
            type:
              name: "properties"
            description: "Additional gRPC configuration properties for IPC gRPC"
            tip: "TODO"
            key: "/ipc/grpc"
            example: "TODO"
            
      # IPC Configuration :: RPC
      - name: "rpc"
        description: "TODO"
        categories:
          # IPC Configuration :: RPC :: Kafka
          - kafka:
            config:
              - name: "Bootstrap servers"
                type:
                  name: "set"
                  items:
                    type:
                      name: "host-with-port"
                    separator: ","
                description: "Kafka bootstrap servers for IPC RPC"
                tip: "TODO"
                key: "/ipc/rpc/kafka/bootstrap.servers"
                example: "TODO"
              - name: "Properties"
                type:
                  name: "properties"
                description: "Additional Kafka configuration properties for IPC RPC"
                tip: "TODO"
                key: "/ipc/rpc/kafka"
                example: "TODO"
                
      # IPC Configuration :: Sink
      - name: "sink"
        description: "TODO"
        categories:
          # IPC Configuration :: Sink :: Kafka
          - name: "kafka"
            config:
              - name: "Bootstrap servers"
                type:
                  name: "set"
                  items:
                    type:
                      name: "host-with-port"
                    separator: ","
                description: "Kafka bootstrap servers for IPC Sink"
                tip: "TODO"
                key: "/ipc/sink/kafka/bootstrap.servers"
                example: "TODO"
              - name: "Properties"
                type:
                  name: "properties"
                description: "Additional Kafka configuration properties for IPC Sink"
                tip: "TODO"
                key: "/ipc/sink/kafka"
                example: "TODO"
                
  # Netmgt
  - name: "netmgt"
    description: "TODO"
    categories:
      # Netmgt :: Traps
      - name: "traps"
        description: "TODO"
        config:
          - name: "Properties"
            type:
              name: "properties"
            description: "TODO"
            tip: "TODO"
            key: "/netmgt/traps"
            example: "TODO"
            
  # Web
  - name: "web"
    description: "TODO"
    categories:
      # Web :: Jetty
      - name: "jetty"
        description: "TODO"
        config:
          - name: "HTTP listen port"
            type:
              name: "port"
            description: "Jetty HTTP listen port"
            tip: "TODO"
            key: "/jetty/web/port"
            example: "TODO"
          - name: "Listen addresses"
            type:
              name: "set"
              items:
                type:
                  name: "host"
                separator: ","
            description: "Jetty listen addresses"
            tip: "TODO"
            key: "/jetty/web/host"
            example: "TODO"
